FROM apache/airflow:2.9.1
ADD requirements.txt .
RUN pip install apache-airflow==${AIRFLOW_VERSION}
USER root
RUN apt-get update
RUN apt-get -y install postgresql python3  libpq-dev python3-dev gcc
USER airflow
RUN pip install -r requirements.txt